server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/mercadolivro?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  flyway:
    baselineOnMigrate: true
    locations: classpath:db/migration
  jackson:
    default-property-inclusion: non_null
